config/routes.rb
Rails.application.routes.draw do
  devise_for :dusers
  get '/about',  to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',  to: 'cookies#new'
  post '/login',  to: 'cookies#create'
  delete '/logout', to: 'cookies#destroy'
  root 'static_pages#home'
  resources :users, only: [:edit, :update]
  resources :courses
  resources :followments, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :old_exams
  resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image
  belongs_to :duser
  belongs_to :old_exam

  validates :content, presence: true, length: { maximum: 255 }
  validate :image?


  private

  def image?
    if image.attached? && !image.content_type.in?(%w(image/jpeg))
      errors.add(:document, 'Must be a jpg image')
    end
  end
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :followments, dependent: :destroy
  has_many :dusers, through: :followments
  has_many :old_exams, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 255 }

  def Course.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/duser.rb
class Duser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followments
  has_many :courses, through: :followments
  has_many :comments
end

app/models/followment.rb
class Followment < ApplicationRecord
  belongs_to :duser
  belongs_to :course
end

app/models/old_exam.rb
class OldExam < ApplicationRecord
  has_one_attached :file
  belongs_to :course
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { maximum: 50 }
  validate :file?


  private

  def file?
    errors.add(:base, 'Please upload exam pdf') unless file.attached?
    if file.attached? && !file.content_type.in?(%w(application/pdf))
      errors.add(:document, 'Must be a PDF file')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def admin_duser!
    if !current_duser.admin?
      flash[:danger] = "YOU ARE NOT AN ADMIN"
      redirect_to root_url
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_duser!
  before_action :admin_duser!, only: :destroy

  def create
    @comment = current_duser.comments.build(user_params)
    if @comment.save
      flash[:success] = "Comment created!"
      redirect_to old_exam_path(@comment.old_exam_id)
    else
      flash[:danger] = "ERROR!"
      redirect_to old_exam_path(@comment.old_exam_id)
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    id = comment.old_exam.id
    comment.destroy
    flash[:success] = "Comment deleted"
    redirect_to old_exam_path(id)
  end


  private

  def user_params
    params.require(:comment).permit(:content, :old_exam_id, :image)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_duser!, only: [:new, :edit, :update, :destroy]
  before_action :admin_duser!, only: [:new, :edit, :update, :destroy]

  def index
    @courses = Course.search(params[:search]).paginate(page: params[:page], per_page: 10)
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(user_params)
    if @course.save
      flash[:success] = "Course created!"
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(user_params)
      flash[:success] = "Successful edit!"
      redirect_to courses_path
    else
      render 'edit'
    end
  end

  def destroy
    Course.find(params[:id]).destroy
    flash[:success] = "Course deleted"
    redirect_to courses_path
  end


  private

  def user_params
    params.require(:course).permit(:name, :description)
  end
end

app/controllers/followments_controller.rb
class FollowmentsController < ApplicationController
  before_action :authenticate_duser!

  def create
    @course = Course.find(params[:course_id])
    if current_duser.courses.exists?(@course.id)
      redirect_to courses_path
    else
      current_duser.courses<<@course
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def destroy
    @course = Followment.find(params[:id]).course
    current_duser.courses.delete(@course)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

end

app/controllers/old_exams_controller.rb
require "google/cloud/storage"

class OldExamsController < ApplicationController
  before_action :authenticate_duser!, only: [:new, :edit, :update, :destroy]
  before_action :admin_duser!, only: [:new, :edit, :update, :destroy]

  def show
    @old_exam = OldExam.find(params[:id])
    @comments = @old_exam.comments.paginate(page: params[:page], per_page: 10)
  end

  def new
    @old_exam = OldExam.new(course_id: params[:course_id])
  end

  def create
    @old_exam = OldExam.new(user_params)
    @old_exam.file.attach(params[:old_exam][:file])

    if @old_exam.save
      flash[:success] = "Exam created!"
      redirect_to course_path(@old_exam.course_id)
    else
      render 'new'
    end
  end

  def edit
    @old_exam = OldExam.find(params[:id])
  end

  def update
    @old_exam = OldExam.find(params[:id])
    id = @old_exam.course_id
    if @old_exam.update_attributes(user_params)
      flash[:success] = "Successful edit!"
      redirect_to course_path(id)
    else
      render 'edit'
    end
  end

  def destroy
    exam = OldExam.find(params[:id])
    id = exam.course_id
    exam.destroy
    flash[:success] = "Exam deleted"
    redirect_to course_path(id)
  end


  private

  def user_params
    params.require(:old_exam).permit(:title, :course_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if duser_signed_in?
      @user ||= current_duser
      @courses = @user.courses
      @courses = @user.courses.paginate(page: params[:page], per_page: 10)
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/followments_helper.rb
module FollowmentsHelper
end

app/helpers/old_exams_helper.rb
module OldExamsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/_course_list.html.erb
<div class="accordion" id="accordionCourses">
  <% @courses.each do |course| %>
    <% @course = course %>
    <div class="card">
      <div class="card-header" id="heading<%= course.id %>">
        <h5 class="mb-0">
          <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse<%= course.id %>" aria-expanded="true" aria-controls="collapse<%= course.id %>">
            <%= course.name %>
          </button>
        </h5>
      </div>

      <div id="collapse<%= course.id %>" class="collapse" aria-labelledby="heading<%= course.id %>" data-parent="#accordionCourses">
        <div class="card-body">
          <p class="card-text"><%= course.description %></p>

          <div class="btn-toolbar" role="toolbar" aria-label="Toolbar courses">

            <div class="btn-group mr-2" role="group" aria-label="First group">
              <%= render 'courses/follow_form' if duser_signed_in? %>
            </div>

            <div class="btn-group mr-2" role="group" aria-label="Second group">
              <%= link_to "Show", course_path(@course.id), class: "btn btn-primary" %>
              <% if current_duser.try(:admin?) and current_page?(controller: 'courses') %>
                <%= link_to "Update", edit_course_path(course.id), class: "btn btn-secondary" %>
                <%= link_to "Delete", course_path(course.id), method: :delete, data: { confirm: "You sure?" }, class: "btn btn-secondary" %>
              <% end %>
            </div>

          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @courses, page_links: false, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/courses/_follow.html.erb
<%= form_for(current_duser.followments.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :course_id, @course.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/courses/_follow_form.html.erb
<div id="<%= "follow_form_#{@course.id}" %>">
  <% if current_duser.courses.exists?(@course.id) %>
    <%= render 'courses/unfollow' %>
  <% else %>
    <%= render 'courses/follow' %>
  <% end %>
</div>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <%# prints out if anny errors in form %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-warning">
        The form contains <%= pluralize(@course.errors.count, "error") %>.
      </div>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter description" %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/courses/_unfollow.html.erb
<%= form_for(current_duser.followments.find_by(course_id: @course.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/courses/edit.html.erb
<% provide(:title, 'Edit Course') %>
<% provide(:button_text, 'Edit course') %>
<h1>Edit course</h1>
<%= render 'form' %>

app/views/courses/index.html.erb
<% provide(:title, "List Courses") %>
<h1>List of available courses</h1>

<%= form_tag(courses_path, method: "get", class: "form-inline my-2 my-lg-0") do %>
  <%= text_field_tag :search, nil, class: "form-control mr-sm-2", type: "search", placeholder: "Search" %>
  <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>

<%= render 'course_list' %>

<% if current_duser.try(:admin?) %>
  <%= link_to "Create new course", new_course_path, class: "btn btn-primary btn-md", role: "button" %>
<% end %>

app/views/courses/new.html.erb
<% provide(:title, "New Courses") %>
<% provide(:button_text, 'Create course') %>
<h1>Create a new course</h1>
<%= render 'form' %>

app/views/courses/show.html.erb
<% provide(:title, "Show Courses") %>
<h1><%= @course.name %></h1>
<div class="card-deck">
  <% @course.old_exams.each do |exam| %>
    <% @old_exam = exam %>
    <%= render 'old_exams/card_old_exam' %>
  <% end %>
</div>

<% if current_duser.try(:admin?) %>
  <%= link_to "Add new exam", new_old_exam_path(course_id: @course.id), class: "btn btn-primary btn-md", role: "button" %>
<% end %>

app/views/followments/create.js.erb
$("<%= "#follow_form_#{@course.id}" %>").html("<%= escape_javascript(render('courses/unfollow')) %>");

app/views/followments/destroy.js.erb
$("<%= "#follow_form_#{@course.id}" %>").html("<%= escape_javascript(render('courses/follow')) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenexaTech | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <%= link_to "MenexaTech", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Courses", courses_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <% if !duser_signed_in? %>
            <li class="nav-item">
              <%= link_to "Login", new_duser_session_path, class: "nav-link" %>
            </li>
          <% end %>

          <% if duser_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Logged in as <%= current_duser.email %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit profile", edit_duser_registration_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Logout", destroy_duser_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>

        </ul>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <%# TODO: come up with a better way to do this %>
        <% if message_type == "notice" %>
          <% message_type = "primary" %>
        <% elsif message_type == "alert" %>
          <% message_type = "warning" %>
        <% elsif message_type == "success" %>
          <% message_type = "success" %>
        <% elsif message_type == "alert" %>
          <% message_type = "danger" %>
        <% end %>

        <div class="<%= "alert alert-#{message_type}" %>"><%= message %></div>
      <% end %>

      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/old_exams/_card_old_exam.html.erb
<div class="card my-3">
  <% if @old_exam.file.previewable? %>
    <%= image_tag(@old_exam.file.preview(resize: "300x300>"), class: "card-img-top") %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= @old_exam.title %> <% if @old_exam.created_at >= 1.day.ago %><span class="badge badge-secondary">New</span><% end %></h5>
    <div class="btn-group-vertical" role="group" aria-label="Old Exam Buttons">
      <%= link_to "Download", rails_blob_path(@old_exam.file, disposition: "attachment"), class: "btn btn-primary btn-md", role: "button" %>
      <%=
        link_to_unless_current "Show", old_exam_path(@old_exam.id), class: "btn btn-primary btn-md", role: "button" do
          link_to "To course", course_path(@old_exam.course.id), class: "btn btn-primary btn-md", role: "button"
        end
      %> 
      <% if current_duser.try(:admin?) %>
        <%= link_to "Update", edit_old_exam_path(@old_exam.id), class: "btn btn-secondary btn-md", role: "button" %>
        <%= link_to "Delete", old_exam_path(@old_exam.id), method: :delete, class: "btn btn-secondary btn-md", role: "button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/old_exams/_form.html.erb
<%= form_for(@old_exam) do |f| %>
  <%# prints out if anny errors in form %>
  <% if @old_exam.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-warning">
        The form contains <%= pluralize(@old_exam.errors.count, "error") %>.
      </div>
      <ul>
        <% @old_exam.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %>
  </div>

  <div class="form-group">
    <%= f.label :file %>
    <%= f.file_field :file, multiple: false %>
  </div>

  <div class="form-group">
    <%= f.label :course_id %>
    <%= f.collection_select :course_id, Course.all, :id, :name %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/old_exams/edit.html.erb
<% provide(:title, 'Edit Old Exam') %>
<% provide(:button_text, 'Edit old exam') %>
<h1>Edit old exam</h1>
<%= render 'form' %>

app/views/old_exams/new.html.erb
<% provide(:title, 'New Old Exam') %>
<% provide(:button_text, 'Create old exam') %>
<h1>Create old exam</h1>
<%= render 'form' %>

app/views/old_exams/show.html.erb
<% provide(:title, 'Show Old Exam') %>
<h1><%= @old_exam.title %></h1>

<div class="row justify-content-center">

  <div class="col-md-4">

    <% if duser_signed_in? %>
      <%= form_for(current_duser.comments.build) do |f| %>
        <% if current_duser.comments.build.errors.any? %>
          bite
        <% end %>
        <div><%= f.hidden_field :old_exam_id, value: @old_exam.id %></div>
        <div class="form-group">
          <%= f.text_area :content, class: "form-control", placeholder: "Enter comment" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, multiple: false, class: "form-control-file" %>
        </div>
        <%= f.submit "Post", class: "btn btn-primary" %>
      <% end %>
    <% end %>
    
    <%= render "card_old_exam" %>

  </div>

  <div class="col-md-8">
    <% @comments.each do |comment| %>
      <div class="list-group list-group-flush">
        <div class="list-group-item">
          <h6>By <%= comment.duser.email %>
          <% if comment.duser.admin? %><span class="badge badge-info">class representative</span><% end %>
          <div class="btn-group">
            <% if current_duser.try(:admin?) %>
              <button type="button" class="btn btn-secondary dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
              <div class="dropdown-menu">
                <%= link_to "Delete", comment_path(comment.id), method: :delete, class: "dropdown-item" %>
              </div>
            <% end %>
          </div></h6>
          <div><%= comment.content %></div>
          <% if comment.image.attached? %>
            <div>
              <a href="<%= rails_blob_path(comment.image, disposition: "attachment") %>">
                <img src="<%= url_for(comment.image) %>" alt="attached image" style="width: 150px;"/>
              </a>
            </div>
          <% end %>
          <small>Posted <%= time_ago_in_words comment.created_at %> ago</small>
        </div>
      </div>
    <% end %>
    <%= will_paginate @comments, page_links: false, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>

</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is a web application allowing students to learn in a more effective
  way. It enables them to share previous exams and their answers as well as
  offering them a place for discussion. You can follow courses and they
  will show up on your home page
</p>
<p>
  If you see any error you can contact me though issues on
  <a href="https://github.com/yannick-mayeur/menexatech_app">GitHub</a>,
  or try to fix it yourself with a Pull Request.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if !duser_signed_in? %>

  <div class="jumbotron">
    <h1 class="display-4">Welcome to MenexaTech</h1>
    <p class="lead">
      This is a web application allowing students to learn in a more effective
      way. It enables them to share previous exams and their answers as well as
      offering them a place for discussion.
    </p>
    <hr class="my-4">
    <p></p>
    <%= link_to "Sign up now", new_duser_registration_path, class: "btn btn-primary btn-lg", role: "button" %>
  </div>

<% else %>

  <% if @user.courses.empty? %>

    <div class="jumbotron">
      <h1 class="display-4">Welcome <%= @user.email %></h1>
      <p class="lead">
        This is a web application allowing students to learn in a more effective
        way. It enables them to share previous exams and their answers as well as
        offering them a place for discussion. You can follow courses and they
        will show up on your home page
      </p>
      <hr class="my-4">
      <p></p>
      <%= link_to "Start following courses now", courses_path, class: "btn btn-primary btn-lg", role: "button" %>
    </div>

  <% else %>
    
    <h1>Followed Courses</h1>
    <%= render 'courses/course_list' %>

  <% end %>

<% end %>